"""仓储抽象接口。

领域代码只依赖该接口；当前提供 SQLite 和内存实现。
关联完整性由服务层在注册表事务内验证。
"""

from __future__ import annotations

from typing import Protocol, TypeVar

from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)


class Repository(Protocol[T]):
    def add(self, item: T) -> T: ...
    def get(self, item_id: str) -> T: ...
    def list(self) -> list[T]: ...
    def update(self, item: T) -> T: ...
    def upsert(self, item: T) -> T: ...
    def delete(self, item_id: str) -> None: ...
    def exists(self, item_id: str) -> bool: ...
    def count(self) -> int: ...
    def clear(self) -> None: ...
